# Generated by Django 4.2.1 on 2023-05-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='availabledoctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100, null=True)),
                ('doctor_email', models.CharField(max_length=200, null=True)),
                ('doctor_age', models.IntegerField(null=True)),
                ('doctor_gender', models.CharField(max_length=6, null=True)),
                ('doctor_mobile', models.CharField(max_length=100, null=True)),
                ('doctor_qualification', models.CharField(max_length=100, null=True)),
                ('doctor_jobstatus', models.CharField(max_length=50, null=True)),
                ('doctor_image', models.CharField(max_length=100, null=True)),
                ('doctor_password', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='doctor_remarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField(null=True)),
                ('case_no', models.IntegerField(null=True)),
                ('doctor_name', models.CharField(max_length=100, null=True)),
                ('doctor_email', models.CharField(max_length=100, null=True)),
                ('doctor_remarks', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='patient_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_username', models.CharField(max_length=100, null=True)),
                ('patient_firstname', models.CharField(max_length=100, null=True)),
                ('patient_secondname', models.CharField(max_length=100, null=True)),
                ('patient_email', models.CharField(max_length=100, null=True)),
                ('patient_password', models.CharField(max_length=100, null=True)),
                ('patient_mobile', models.CharField(max_length=100, null=True)),
                ('patient_gender', models.CharField(max_length=6, null=True)),
                ('patient_dob', models.DateField(null=True)),
                ('patient_civilstatus', models.CharField(max_length=20, null=True)),
                ('patient_age', models.IntegerField(null=True)),
                ('patient_image', models.ImageField(null=True, upload_to='Templates/images')),
            ],
        ),
        migrations.CreateModel(
            name='patient_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField(null=True)),
                ('case_no', models.IntegerField(null=True)),
                ('model_prediction', models.CharField(max_length=100, null=True)),
                ('underweight', models.CharField(max_length=10, null=True)),
                ('constipation', models.CharField(max_length=10, null=True)),
                ('abdominalproblem', models.CharField(max_length=10, null=True)),
                ('heartproblem', models.CharField(max_length=10, null=True)),
                ('anyseriousinjury', models.CharField(max_length=10, null=True)),
                ('kidneybladderinfection', models.CharField(max_length=10, null=True)),
                ('asthma', models.CharField(max_length=10, null=True)),
                ('skinalergy', models.CharField(max_length=10, null=True)),
                ('brokenbones', models.CharField(max_length=10, null=True)),
                ('visiteddoctorbefore', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='patienttodoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField(null=True)),
                ('patient_firstname', models.CharField(max_length=100, null=True)),
                ('patient_email', models.CharField(max_length=100, null=True)),
                ('patient_mobile', models.CharField(max_length=100, null=True)),
                ('case_no', models.IntegerField(null=True)),
                ('doctor_id', models.IntegerField(null=True)),
                ('patient_image', models.CharField(max_length=300, null=True)),
                ('respond', models.CharField(max_length=5, null=True)),
            ],
        ),
    ]
