# Generated by Django 4.2 on 2023-05-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_alter_patient_details_patient_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_history',
            name='constipation',
        ),
        migrations.RemoveField(
            model_name='patient_history',
            name='underweight',
        ),
        migrations.AlterField(
            model_name='patient_details',
            name='patient_image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
