# Generated by Django 4.2 on 2023-05-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_remove_patient_history_constipation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_history',
            name='case_no',
            field=models.CharField(max_length=99999, null=True),
        ),
    ]
