# Generated by Django 4.2 on 2023-05-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_alter_patient_history_case_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_history',
            name='case_no',
            field=models.IntegerField(null=True),
        ),
    ]
