# Generated by Django 4.2.1 on 2023-06-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_alter_patient_history_case_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienttodoctor',
            name='respond',
            field=models.CharField(default='No', max_length=5),
        ),
    ]
