# Generated by Django 4.2.1 on 2023-06-01 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_alter_patienttodoctor_respond'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patienttodoctor',
            old_name='respond',
            new_name='doctor_respond',
        ),
    ]
