# Generated by Django 4.2 on 2023-06-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_rename_respond_patienttodoctor_doctor_respond'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienttodoctor',
            name='doctor_respond',
            field=models.CharField(default='No', max_length=500),
        ),
    ]
