# Generated by Django 4.2 on 2023-06-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_alter_patienttodoctor_doctor_respond'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabledoctors',
            name='doctor_image',
            field=models.ImageField(default='', upload_to='db_images/images'),
        ),
        migrations.AlterField(
            model_name='patient_details',
            name='patient_image',
            field=models.ImageField(default='', upload_to='db_images/images'),
        ),
    ]
