# Generated by Django 4.2 on 2023-06-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0009_alter_availabledoctors_doctor_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabledoctors',
            name='doctor_image',
            field=models.ImageField(default='', upload_to='db_images/doctor_images'),
        ),
    ]
