# Generated by Django 4.2 on 2023-06-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_alter_availabledoctors_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_details',
            name='patient_image',
            field=models.ImageField(default='', upload_to='db_images/patient_images'),
        ),
    ]
