# Generated by Django 4.2.1 on 2023-06-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MainApp", "0011_alter_patient_details_patient_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient_details",
            name="patient_image",
            field=models.ImageField(null=True, upload_to="db_images/patient_images"),
        ),
    ]
