# Generated by Django 4.2.1 on 2023-06-26 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MainApp", "0012_alter_patient_details_patient_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="admin_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admin_name", models.CharField(max_length=100, null=True)),
                ("admin_email", models.CharField(max_length=100, null=True)),
                ("admin_password", models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
