# Generated by Django 5.0.6 on 2024-11-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MainApp", "0013_admin_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient_details",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="patient_details",
            name="patient_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="db_images/patient_images"
            ),
        ),
    ]
